# fly.toml app configuration file generated for undi on 2023-10-26T15:45:47+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "undi"
primary_region = "sin"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "undi.fly.dev"
  PORT = "8080"
  DNS_CLUSTER_QUERY = "undi.internal"
  RELEASE_COOKIE = "q9MxWqINsox_vlQpO9lxcOHK_8SYeJLnXDWxqw7huaciVUeEe-foMA=="

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
